// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaceEvents.Data;

#nullable disable

namespace RaceEvents.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RaceEvents.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("HelmetType")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("EventId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("RaceEvents.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CarClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("DriveType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("Horsepower")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("ParticipantId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("RaceEvents.Models.Championship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MinPodiumsRequired")
                        .HasColumnType("int");

                    b.Property<string>("RequiredCarClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.ToTable("Championships");
                });

            modelBuilder.Entity("RaceEvents.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<int>("CarTypeRequirement")
                        .HasColumnType("int");

                    b.Property<int?>("ChampionshipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("MaxHorsepower")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("RequiredCarClass")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RequiredDriveType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TrackType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("ChampionshipId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RaceEvents.Models.FinalResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("AverageLapTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("BestLapTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("TotalLaps")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TotalTime")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("FinalResults");
                });

            modelBuilder.Entity("RaceEvents.Models.LapTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("LapNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("LapTimes");
                });

            modelBuilder.Entity("RaceEvents.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("RaceEvents.Models.Administrator", b =>
                {
                    b.HasBaseType("RaceEvents.Models.User");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.ToTable("Administrators", (string)null);
                });

            modelBuilder.Entity("RaceEvents.Models.Participant", b =>
                {
                    b.HasBaseType("RaceEvents.Models.User");

                    b.Property<TimeSpan?>("BestLapTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DriverLicense")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PodiumCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("RaceEvents.Models.Application", b =>
                {
                    b.HasOne("RaceEvents.Models.Car", "Car")
                        .WithMany("Applications")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceEvents.Models.Event", "Event")
                        .WithMany("Applications")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceEvents.Models.Participant", "Participant")
                        .WithMany("Applications")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Event");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("RaceEvents.Models.Car", b =>
                {
                    b.HasOne("RaceEvents.Models.Participant", "Participant")
                        .WithMany("Cars")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("RaceEvents.Models.Championship", b =>
                {
                    b.HasOne("RaceEvents.Models.Administrator", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("RaceEvents.Models.Event", b =>
                {
                    b.HasOne("RaceEvents.Models.Administrator", "Administrator")
                        .WithMany("Events")
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceEvents.Models.Championship", "Championship")
                        .WithMany("Events")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Administrator");

                    b.Navigation("Championship");
                });

            modelBuilder.Entity("RaceEvents.Models.FinalResult", b =>
                {
                    b.HasOne("RaceEvents.Models.Application", "Application")
                        .WithOne("FinalResult")
                        .HasForeignKey("RaceEvents.Models.FinalResult", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("RaceEvents.Models.LapTime", b =>
                {
                    b.HasOne("RaceEvents.Models.Application", "Application")
                        .WithMany("LapTimes")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("RaceEvents.Models.Administrator", b =>
                {
                    b.HasOne("RaceEvents.Models.User", null)
                        .WithOne()
                        .HasForeignKey("RaceEvents.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaceEvents.Models.Participant", b =>
                {
                    b.HasOne("RaceEvents.Models.User", null)
                        .WithOne()
                        .HasForeignKey("RaceEvents.Models.Participant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaceEvents.Models.Application", b =>
                {
                    b.Navigation("FinalResult");

                    b.Navigation("LapTimes");
                });

            modelBuilder.Entity("RaceEvents.Models.Car", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("RaceEvents.Models.Championship", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("RaceEvents.Models.Event", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("RaceEvents.Models.Administrator", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("RaceEvents.Models.Participant", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
